eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eurekaserver
    instance:
      hostname: localhost
      
  microservice:
    paymentservice:
      endpoints:
        endpoint:
          uri: http://PAYMENT-SERVICE/payment/makePayment
    orderservice:
      endpoints:
        endpoint:
          uri: http://ORDER-SERVICE/order/placeOrder
