server:
  port: 9192
spring:
 application:
    name: CONFIG-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eurekaserver
